### ISSUE TITLE
Transfer to @ryanheath

### ISSUE THREAD

**Issue by mj1856** [ryanheath/RavenDB-NodaTime#19]
Given the current state of things, I'd like to transfer full control of this repo to @ryanheath and move it to `ryanheath/RavenDB-NodaTime`.

Any objections?

**Comment by ryanheath** [comment]
Let's give it some time, when nobody objects I ok with it.

// Ryan

**Comment by ryanheath** [comment]
Done!

// Ryan

**Comment by mj1856** [comment]
Hey, sorry I forgot to get back to this.  Seems like GitHub won't let me transfer it if you have a fork at all.  I get "ryanheath already has a repository in the mj1856/RavenDB-NodaTime network" when I try.  I'd say, make sure you don't have anything pending, then delete your fork.   Then I can try again.

**Comment by ryanheath** [comment]
I've deleted my fork, it should work now.

// Ryan

**Comment by mj1856** [comment]
Success! You should have an invite to take ownership.

**Comment by ryanheath** [comment]
Oops! That repository transfer has expired.

I've seen that invite too late ...

**Comment by mj1856** [comment]
New one sent

**Comment by ryanheath** [comment]
Thanks, it is transfered.

**Comment by tobiaszuercher** [comment]
sorry for reopen.

i just wanted to post that i'm interested to keep this updated. i have my personal fork for two other projects, which i dont like. i'd prefer to get this over nuget. 

it got moved now to ryanheath, but it's still not updated :)

does it make sense to move to https://github.com/ravendb/ravendb.contrib so we can have multiple users contributing to it?

again: i'm really interested in keeping this updated.

**Comment by ryanheath** [comment]
Hi Tobias,

What do you refer to as not updated?

Everyone can contribute. Just send in a PR. 😀

// Ryan
