### ISSUE TITLE
RavenDB 4.2 support?

### ISSUE THREAD

**Issue by Bishbulb** [ryanheath/RavenDB-NodaTime#20]
Is there any possibility of getting a release that supports RavenDB 4.2? If its just a matter of updating dependencies, I can create a pull request if that would help.

**Comment by ryanheath** [comment]
Hi Dan,

It seems not that easy. I'm looking into it.

**Comment by ryanheath** [comment]
Upgrade has finished, it should be available shortly at nuget
https://www.nuget.org/packages/RavenDB.Client.NodaTime/

Let me know if you run into any issues.

// #Ryan

**Comment by Bishbulb** [comment]
@ryanheath Awesome, thanks so much for the quick turnaround!
