### ISSUE TITLE
Unable to query ZonedDateTime when using RavenDB.Client >= 5.3.100

### ISSUE THREAD

**Issue by wagich** [ryanheath/RavenDB-NodaTime#29]
When trying to query a `ZonedDateTime` property (using `ToInstant()`), the query processing blows up with `MissingMethodException: Method not found: 'Result Raven.Client.Documents.Linq.LinqPathProvider.GetPath(System.Linq.Expressions.Expression)'.`.

It looks like the signature of `GetPath` changed in RavenDB 5.3.100 (see https://github.com/ravendb/ravendb/commit/ea67ed339fe38618c5cafc8f4ea999de854feeb1 for the diff) causing the failure.

Would you be able to release a new version of the package compiled against RavenDB.Client 5.3.100 or higher?

**Comment by ryanheath** [comment]
Do you have a failing test for this problem?

**Comment by wagich** [comment]
I've created a test project at https://github.com/wagich/ReplicateZonedDateTimeQueryProblem.

The issue can also be replicated in the integrated test project by replacing the ProjectReference to `Raven.Client.NodaTime.csproj` with a package reference to the nuget package `RavenDB.Client.NodaTime`.

**Comment by ryanheath** [comment]
fixed with [v5.3.102](https://www.nuget.org/packages/RavenDB.Client.NodaTime/5.3.102)
